find_package(OpenGL REQUIRED COMPONENTS OpenGL)
find_package(glad2cmake CONFIG REQUIRED)
find_package(SQLiteCpp CONFIG REQUIRED)
find_package(Freetype REQUIRED)
find_package(GTest CONFIG REQUIRED)
find_package(glfw3 CONFIG REQUIRED)
find_package(glm CONFIG REQUIRED)
find_package(spdlog CONFIG REQUIRED)
find_package(nlohmann_json CONFIG REQUIRED)
find_package(valijson CONFIG REQUIRED)
find_package(fmt CONFIG REQUIRED)
